#!/bin/bash
# Script to remove duplicate skills from node-registry
# These skills exist in core-registry with optimized Rust/WASM implementations

# List of 66 duplicate skills to remove from node-registry
# (keeping core-registry versions which are WASM/Rust optimized)

DUPLICATES=(
    "agents-list"
    "agent-step"
    "browser-automation"
    "browser-click"
    "browser-navigate"
    "browser-pdf"
    "browser-screenshot"
    "browser-type"
    "canvas-render"
    "cascade-run"
    "code-format"
    "cron-add"
    "cron-list"
    "cron-remove"
    "cron-run"
    "cron-schedule"
    "discord-send"
    "disk-usage"
    "docker-exec"
    "docker-logs"
    "docker-stats"
    "email-send"
    "env-get"
    "file-delete"
    "file-move"
    "file-search"
    "file-write"
    "gateway-config"
    "gateway-query"
    "gateway-restart"
    "gateway-update"
    "git-branch"
    "git-commit"
    "git-diff"
    "git-log"
    "hash-file"
    "http-request"
    "image-analyze"
    "image-generate"
    "json-transform"
    "markdown-parse"
    "memory-read"
    "memory-write"
    "message-send"
    "model-usage"
    "network-stats"
    "nodes-list"
    "openai-image-gen"
    "process-list"
    "session-history"
    "session-list"
    "session-spawn"
    "session-status"
    "slack-channel"
    "slack-file"
    "slack-react"
    "slack-send"
    "telegram-group"
    "telegram-media"
    "telegram-send"
    "text-search"
    "text-to-speech"
    "web-fetch"
    "web-search"
    "whatsapp-send"
    "yaml-parse"
)

echo "Removing ${#DUPLICATES[@]} duplicate skills from node-registry..."
echo "(Keeping core-registry versions with optimized Rust/WASM implementations)"
echo ""

for skill in "${DUPLICATES[@]}"; do
    if [ -d "skills/node-registry/$skill" ]; then
        echo "Removing: $skill"
        git rm -r "skills/node-registry/$skill" 2>/dev/null || rm -rf "skills/node-registry/$skill"
    else
        echo "Already removed: $skill"
    fi
done

echo ""
echo "Duplicate removal complete!"
echo ""
echo "New counts:"
echo "  node-registry: $((434 - 66)) = 368 skills"
echo "  core-registry: 231 skills"
echo "  python-registry: 25 skills"
echo "  TOTAL: 624 unique skills"
